services:
  - type: web
    name: sync-video-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    rootDir: Ver-videos-mp4-con-amigos
